## Datatypes and atteibutes

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a1.dtype 

dtype('int32')

In [6]:
type(a1) # default arrray of numpy

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.5],
              [4, 5, 6]])
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [7]:
a2.dtype, a2.size, type(a2)

(dtype('float64'), 6, numpy.ndarray)

In [32]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a3.shape, a3.ndim

((2, 3, 3), 3)

In [34]:
import pandas as pd

In [36]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.0

## Creating Arrays

In [10]:
a4 = np.arange(0, 10, 2) #Return evenly spaced values within a given interval.
a4

array([0, 2, 4, 6, 8])

In [11]:
a4.dtype, a4.size, a4.ndim

(dtype('int32'), 5, 1)

In [15]:
a5 = np.random.randint(60, size=(2, 2, 3, 5))
a5

array([[[[37, 42, 10, 17,  9],
         [ 6, 52, 31, 10, 54],
         [14,  6, 52, 24,  9]],

        [[30, 47, 39, 41, 46],
         [ 1, 12, 19, 25, 54],
         [ 1, 15, 47,  0,  2]]],


       [[[34,  8, 49, 30, 32],
         [38, 29,  3, 27, 39],
         [54, 40, 13, 54, 17]],

        [[47, 28, 49, 47, 38],
         [14,  0, 23, 54, 19],
         [46, 52, 24, 43, 23]]]])

In [16]:
a5.ndim, type(a5)  # this is a 4d array.

(4, numpy.ndarray)

In [19]:
zeros = np.zeros((1, 3, 4))  #Return a new array of given shape and type,
                          #filled with zeros.
zeros, zeros.dtype, zeros.ndim # zero array sometime useful in dimensional matching.

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 dtype('float64'),
 3)

In [20]:
ones =np.ones((2, 2, 3, 5))
ones, ones.dtype, ones.ndim

(array([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]]),
 dtype('float64'),
 4)

In [22]:
a6 = np.random.random((3, 5))
a6

array([[0.22611428, 0.6197134 , 0.31454489, 0.9441255 , 0.10092961],
       [0.33374318, 0.78584084, 0.92365688, 0.8746903 , 0.54282118],
       [0.55062952, 0.86631214, 0.97260438, 0.10326688, 0.888435  ]])

In [25]:
np.random.seed(123) # Pseudo random no. used to reproduce our results.
a7 = np.random.random((3, 5))
a7

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]])

In [29]:
a7 = np.random.random((3, 5))
a7, a7.dtype, a7.ndim

(array([[0.66931378, 0.58593655, 0.6249035 , 0.67468905, 0.84234244],
        [0.08319499, 0.76368284, 0.24366637, 0.19422296, 0.57245696],
        [0.09571252, 0.88532683, 0.62724897, 0.72341636, 0.01612921]]),
 dtype('float64'),
 2)